# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HW.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os
from PyQt5.QtCore import pyqtSlot
from PyQt5.QtWidgets import *
from PyQt5.QtWidgets import QApplication, QWidget, QLabel
from PyQt5.QtGui import QIcon, QPixmap
import dense_unet

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1154, 858)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(800, 810, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.selectImage = QtWidgets.QPushButton(Dialog)
        self.selectImage.setGeometry(QtCore.QRect(30, 20, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.selectImage.setFont(font)
        self.selectImage.setObjectName("selectImage")
        self.selectModel = QtWidgets.QPushButton(Dialog)
        self.selectModel.setGeometry(QtCore.QRect(580, 20, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.selectModel.setFont(font)
        self.selectModel.setObjectName("selectModel")
        self.run = QtWidgets.QPushButton(Dialog)
        self.run.setGeometry(QtCore.QRect(780, 20, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.run.setFont(font)
        self.run.setObjectName("run")
        self.dice_1 = QtWidgets.QLabel(Dialog)
        self.dice_1.setGeometry(QtCore.QRect(980, 30, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dice_1.setFont(font)
        self.dice_1.setObjectName("dice_1")
        self.dice_2 = QtWidgets.QLabel(Dialog)
        self.dice_2.setGeometry(QtCore.QRect(980, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dice_2.setFont(font)
        self.dice_2.setObjectName("dice_2")
        self.dice_3 = QtWidgets.QLabel(Dialog)
        self.dice_3.setGeometry(QtCore.QRect(980, 110, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dice_3.setFont(font)
        self.dice_3.setObjectName("dice_3")
        self.dice_4 = QtWidgets.QLabel(Dialog)
        self.dice_4.setGeometry(QtCore.QRect(980, 150, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dice_4.setFont(font)
        self.dice_4.setObjectName("dice_4")
        self.dice_5 = QtWidgets.QLabel(Dialog)
        self.dice_5.setGeometry(QtCore.QRect(980, 190, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dice_5.setFont(font)
        self.dice_5.setObjectName("dice_5")
        self.dice_6 = QtWidgets.QLabel(Dialog)
        self.dice_6.setGeometry(QtCore.QRect(980, 230, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dice_6.setFont(font)
        self.dice_6.setObjectName("dice_6")
        self.dice_7 = QtWidgets.QLabel(Dialog)
        self.dice_7.setGeometry(QtCore.QRect(980, 270, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dice_7.setFont(font)
        self.dice_7.setObjectName("dice_7")
        self.dice_8 = QtWidgets.QLabel(Dialog)
        self.dice_8.setGeometry(QtCore.QRect(980, 310, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dice_8.setFont(font)
        self.dice_8.setObjectName("dice_8")
        self.dice_9 = QtWidgets.QLabel(Dialog)
        self.dice_9.setGeometry(QtCore.QRect(980, 350, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dice_9.setFont(font)
        self.dice_9.setObjectName("dice_9")
        self.dice_10 = QtWidgets.QLabel(Dialog)
        self.dice_10.setGeometry(QtCore.QRect(980, 390, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dice_10.setFont(font)
        self.dice_10.setObjectName("dice_10")
        self.dice_11 = QtWidgets.QLabel(Dialog)
        self.dice_11.setGeometry(QtCore.QRect(980, 430, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dice_11.setFont(font)
        self.dice_11.setObjectName("dice_11")
        self.dice_12 = QtWidgets.QLabel(Dialog)
        self.dice_12.setGeometry(QtCore.QRect(980, 470, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dice_12.setFont(font)
        self.dice_12.setObjectName("dice_12")
        self.dice_13 = QtWidgets.QLabel(Dialog)
        self.dice_13.setGeometry(QtCore.QRect(980, 510, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dice_13.setFont(font)
        self.dice_13.setObjectName("dice_13")
        self.dice_14 = QtWidgets.QLabel(Dialog)
        self.dice_14.setGeometry(QtCore.QRect(980, 550, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dice_14.setFont(font)
        self.dice_14.setObjectName("dice_14")
        self.dice_15 = QtWidgets.QLabel(Dialog)
        self.dice_15.setGeometry(QtCore.QRect(980, 590, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dice_15.setFont(font)
        self.dice_15.setObjectName("dice_15")
        self.dice_16 = QtWidgets.QLabel(Dialog)
        self.dice_16.setGeometry(QtCore.QRect(980, 630, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dice_16.setFont(font)
        self.dice_16.setObjectName("dice_16")
        self.dice_17 = QtWidgets.QLabel(Dialog)
        self.dice_17.setGeometry(QtCore.QRect(980, 670, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dice_17.setFont(font)
        self.dice_17.setObjectName("dice_17")
        self.dice_18 = QtWidgets.QLabel(Dialog)
        self.dice_18.setGeometry(QtCore.QRect(980, 710, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dice_18.setFont(font)
        self.dice_18.setObjectName("dice_18")
        self.dice_Avg = QtWidgets.QLabel(Dialog)
        self.dice_Avg.setGeometry(QtCore.QRect(980, 750, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dice_Avg.setFont(font)
        self.dice_Avg.setObjectName("dice_Avg")
        self.image_name = QtWidgets.QLabel(Dialog)
        self.image_name.setGeometry(QtCore.QRect(40, 790, 761, 19))
        self.image_name.setObjectName("image_name")
        self.image = QtWidgets.QLabel(Dialog)
        self.image.setGeometry(QtCore.QRect(40, 100, 271, 661))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.image.setFont(font)
        self.image.setObjectName("image")
        self.gt_image = QtWidgets.QLabel(Dialog)
        self.gt_image.setGeometry(QtCore.QRect(350, 100, 271, 671))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.gt_image.setFont(font)
        self.gt_image.setObjectName("gt_image")
        self.y_image = QtWidgets.QLabel(Dialog)
        self.y_image.setGeometry(QtCore.QRect(670, 100, 271, 671))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.y_image.setFont(font)
        self.y_image.setObjectName("y_image")
        self.selectGt = QtWidgets.QPushButton(Dialog)
        self.selectGt.setGeometry(QtCore.QRect(340, 20, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.selectGt.setFont(font)
        self.selectGt.setObjectName("selectGt")
        self.gt_name = QtWidgets.QLabel(Dialog)
        self.gt_name.setGeometry(QtCore.QRect(40, 820, 761, 19))
        self.gt_name.setObjectName("gt_name")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.selectImage.setText(_translate("Dialog", "Select Image"))
        self.selectModel.setText(_translate("Dialog", "Select Model"))
        self.run.setText(_translate("Dialog", "Run"))
        self.dice_1.setText(_translate("Dialog", "DC1"))
        self.dice_2.setText(_translate("Dialog", "DC2"))
        self.dice_3.setText(_translate("Dialog", "DC3"))
        self.dice_4.setText(_translate("Dialog", "DC4"))
        self.dice_5.setText(_translate("Dialog", "DC5"))
        self.dice_6.setText(_translate("Dialog", "DC6"))
        self.dice_7.setText(_translate("Dialog", "DC7"))
        self.dice_8.setText(_translate("Dialog", "DC8"))
        self.dice_9.setText(_translate("Dialog", "DC9"))
        self.dice_10.setText(_translate("Dialog", "DC10"))
        self.dice_11.setText(_translate("Dialog", "DC11"))
        self.dice_12.setText(_translate("Dialog", "DC12"))
        self.dice_13.setText(_translate("Dialog", "DC13"))
        self.dice_14.setText(_translate("Dialog", "DC14"))
        self.dice_15.setText(_translate("Dialog", "DC15"))
        self.dice_16.setText(_translate("Dialog", "DC16"))
        self.dice_17.setText(_translate("Dialog", "DC17"))
        self.dice_18.setText(_translate("Dialog", "DC18"))
        self.dice_Avg.setText(_translate("Dialog", "DCAvg"))
        self.image_name.setText(_translate("Dialog", "TextLabel"))
        self.image.setText(_translate("Dialog", "image"))
        self.gt_image.setText(_translate("Dialog", "ground truth image"))
        self.y_image.setText(_translate("Dialog", "predict image"))
        self.selectGt.setText(_translate("Dialog", "Select GT"))
        self.gt_name.setText(_translate("Dialog", "TextLabel"))

        self.selectImage.clicked.connect(self.selectImageFunction)
        self.selectGt.clicked.connect(self.selectGTFunction)
        self.selectModel.clicked.connect(self.selectModelFunction)
        self.run.clicked.connect(self.predict)

    def selectImageFunction(self):
        self.image_file_name = QFileDialog.getOpenFileName()[0]
        self.image_name.setText(self.image_file_name)
        pixmap = QPixmap(QPixmap(self.image_file_name))

        w = self.image.width();
        h = self.image.height();

        self.image.setPixmap(pixmap.scaled(w,h))
        self.image.show()

    def selectGTFunction(self):
        self.gt_file_name = QFileDialog.getOpenFileName()[0]
        self.gt_name.setText(self.gt_file_name)
        pixmap = QPixmap(QPixmap(self.gt_file_name))

        w = self.gt_image.width();
        h = self.gt_image.height();

        self.gt_image.setPixmap(pixmap.scaled(w,h))
        self.gt_image.show()

    def selectModelFunction(self):
        self.model_file_name = QFileDialog.getOpenFileName()[0]
        print(self.model_file_name)

    def predict(self):
        print("predict!!!", self.model_file_name, self.gt_file_name, self.image_file_name)
        if(not self.model_file_name or not self.gt_file_name or not self.image_file_name):
            print("something wrong")
            return
        else:
            sep_dice_result, dice_result = dense_unet.run(self.model_file_name, self.image_file_name, self.gt_file_name)
            _translate = QtCore.QCoreApplication.translate
            self.dice_1.setText(_translate("Dialog", "DC1:"+str(format(sep_dice_result[0], '.2f'))))
            self.dice_2.setText(_translate("Dialog", "DC2:"+str(format(sep_dice_result[1], '.2f'))))
            self.dice_3.setText(_translate("Dialog", "DC3:"+str(format(sep_dice_result[2], '.2f'))))
            self.dice_4.setText(_translate("Dialog", "DC4:"+str(format(sep_dice_result[3], '.2f'))))
            self.dice_5.setText(_translate("Dialog", "DC5:"+str(format(sep_dice_result[4], '.2f'))))
            self.dice_6.setText(_translate("Dialog", "DC6:"+str(format(sep_dice_result[5], '.2f'))))
            self.dice_7.setText(_translate("Dialog", "DC7:"+str(format(sep_dice_result[6], '.2f'))))
            self.dice_8.setText(_translate("Dialog", "DC8:"+str(format(sep_dice_result[7], '.2f'))))
            self.dice_9.setText(_translate("Dialog", "DC9:"+str(format(sep_dice_result[8], '.2f'))))
            self.dice_10.setText(_translate("Dialog", "DC10:"+str(format(sep_dice_result[10], '.2f'))))
            self.dice_11.setText(_translate("Dialog", "DC11:"+str(format(sep_dice_result[11], '.2f'))))
            self.dice_12.setText(_translate("Dialog", "DC12:"+str(format(sep_dice_result[12], '.2f'))))
            self.dice_13.setText(_translate("Dialog", "DC13:"+str(format(sep_dice_result[13], '.2f'))))
            self.dice_14.setText(_translate("Dialog", "DC14:"+str(format(sep_dice_result[14], '.2f'))))
            self.dice_15.setText(_translate("Dialog", "DC15:"+str(format(sep_dice_result[15], '.2f'))))
            self.dice_16.setText(_translate("Dialog", "DC16:"+str(format(sep_dice_result[16], '.2f'))))
            self.dice_17.setText(_translate("Dialog", "DC17:"+str(format(sep_dice_result[17], '.2f'))))
            self.dice_18.setText(_translate("Dialog", "DC18:"+str(format(sep_dice_result[18], '.2f'))))
            self.dice_Avg.setText(_translate("Dialog", "DCAvg:"+str(format(dice_result[0][0], '.2f'))))

        pixmap = QPixmap(QPixmap('./output.png'))

        w = self.y_image.width();
        h = self.y_image.height();

        self.y_image.setPixmap(pixmap.scaled(w,h))
        self.y_image.show()

    model_file_name = ""
    gt_file_name = ""
    image_file_name = ""

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
